# Generated by Django 2.1.5 on 2019-09-22 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='icon',
            field=models.CharField(max_length=100, null=True, verbose_name='副本图标'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
